export function dashboardPage(): string {
  return `<!doctype html>
<html lang="id">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="dark">
  <title>Personal AI Vault</title>
  <style>
    :root{--bg:#0a0d0c;--panel:#111614;--panel2:#171d1a;--line:#27302b;--text:#f2f5f3;--muted:#98a49e;--green:#b7f34a;--green2:#213510;--danger:#ff837b;--shadow:0 24px 70px rgba(0,0,0,.32)}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 85% -10%,#1c2e19 0,transparent 33%),var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;min-height:100vh}
    button,input,textarea{font:inherit}.shell{max-width:1440px;margin:auto;padding:22px}.topbar{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);padding:4px 0 20px}.brand{display:flex;gap:12px;align-items:center}.brandmark{width:38px;height:38px;border-radius:12px;background:var(--green);color:#111;display:grid;place-items:center;font-weight:900}.brand h1{font-size:17px;margin:0;letter-spacing:.01em}.brand p{font-size:12px;color:var(--muted);margin:3px 0 0}.health{display:flex;gap:8px;align-items:center;color:var(--muted);font-size:13px}.dot{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 0 5px rgba(183,243,74,.09)}
    .layout{display:grid;grid-template-columns:230px 1fr;gap:22px;padding-top:22px}.sidebar{background:rgba(17,22,20,.72);border:1px solid var(--line);border-radius:18px;padding:14px;height:max-content;position:sticky;top:20px}.nav{display:grid;gap:6px}.nav button{border:0;background:transparent;color:var(--muted);padding:11px 12px;text-align:left;border-radius:10px;cursor:pointer}.nav button.active,.nav button:hover{background:var(--green2);color:var(--green)}.side-note{border-top:1px solid var(--line);margin-top:15px;padding:15px 8px 4px;color:var(--muted);font-size:12px;line-height:1.55}
    main{min-width:0}.hero{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin:3px 0 20px}.eyebrow{color:var(--green);text-transform:uppercase;letter-spacing:.16em;font-size:11px;font-weight:750}.hero h2{font-family:Georgia,serif;font-weight:500;font-size:clamp(32px,5vw,54px);line-height:1;margin:7px 0 9px}.hero p{color:var(--muted);margin:0;max-width:650px}.actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.btn{border:1px solid var(--line);color:var(--text);background:var(--panel2);padding:10px 14px;border-radius:11px;cursor:pointer;font-weight:650;font-size:13px}.btn:hover{border-color:#536158}.btn.primary{background:var(--green);border-color:var(--green);color:#111}.btn.danger{color:var(--danger)}
    .stats{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px;margin-bottom:20px}.stat{background:linear-gradient(145deg,rgba(23,29,26,.95),rgba(14,18,16,.94));border:1px solid var(--line);border-radius:15px;padding:16px;box-shadow:var(--shadow)}.stat span{display:block;color:var(--muted);font-size:12px}.stat strong{display:block;font-family:Georgia,serif;font-size:30px;font-weight:500;margin-top:8px}
    .workspace{background:rgba(17,22,20,.88);border:1px solid var(--line);border-radius:18px;overflow:hidden;box-shadow:var(--shadow)}.toolbar{display:flex;justify-content:space-between;gap:12px;padding:14px;border-bottom:1px solid var(--line)}.search{display:flex;align-items:center;gap:8px;flex:1;max-width:520px;background:#0b0f0d;border:1px solid var(--line);border-radius:11px;padding:0 12px}.search input{border:0;outline:0;background:transparent;color:var(--text);padding:10px 0;width:100%}.crumbs{display:flex;align-items:center;gap:7px;padding:13px 16px;color:var(--muted);font-size:13px;border-bottom:1px solid var(--line)}.crumbs button{border:0;background:transparent;color:var(--green);cursor:pointer;padding:0}.table-head,.row{display:grid;grid-template-columns:minmax(220px,1fr) 110px 110px 170px 140px;align-items:center;gap:12px}.table-head{padding:10px 16px;color:#77827c;text-transform:uppercase;font-size:10px;letter-spacing:.1em}.row{padding:13px 16px;border-top:1px solid rgba(39,48,43,.72)}.row:hover{background:#141b17}.name{display:flex;align-items:center;gap:11px;min-width:0}.icon{width:36px;height:36px;border:1px solid var(--line);border-radius:10px;display:grid;place-items:center;background:#0d120f}.name button{border:0;background:transparent;color:var(--text);padding:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:left;cursor:pointer}.meta{color:var(--muted);font-size:12px}.row-actions{display:flex;gap:5px;justify-content:flex-end}.icon-btn{border:1px solid transparent;background:transparent;color:var(--muted);cursor:pointer;border-radius:8px;padding:6px 8px}.icon-btn:hover{border-color:var(--line);color:var(--text)}.empty{padding:65px 20px;text-align:center;color:var(--muted)}
    dialog{color:var(--text);background:var(--panel);border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow);width:min(480px,calc(100% - 28px));padding:0}dialog::backdrop{background:rgba(0,0,0,.7)}.modal{padding:20px}.modal h3{margin:0 0 6px}.modal p{color:var(--muted);font-size:13px;margin:0 0 18px}.field{display:grid;gap:7px;margin:12px 0}.field label{font-size:12px;color:var(--muted)}.field input,.field textarea{border:1px solid var(--line);border-radius:10px;background:#0b0f0d;color:var(--text);padding:11px;outline:none}.field textarea{min-height:130px;resize:vertical}.modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.toast{position:fixed;right:22px;bottom:22px;background:#202923;border:1px solid #3a493f;border-radius:12px;padding:12px 15px;box-shadow:var(--shadow);opacity:0;transform:translateY(8px);pointer-events:none;transition:.2s}.toast.show{opacity:1;transform:none}.hidden{display:none!important}
    @media(max-width:960px){.layout{grid-template-columns:1fr}.sidebar{position:static}.nav{grid-template-columns:repeat(2,1fr)}.side-note{display:none}.stats{grid-template-columns:repeat(2,1fr)}.table-head{display:none}.row{grid-template-columns:minmax(0,1fr) auto}.row>.meta:nth-of-type(2),.row>.meta:nth-of-type(3){display:none}.row-actions{grid-column:2}.hero{align-items:flex-start;flex-direction:column}.actions{justify-content:flex-start}}
    @media(max-width:560px){.shell{padding:14px}.topbar .health span:last-child{display:none}.stats{grid-template-columns:1fr 1fr}.stat strong{font-size:24px}.toolbar{flex-direction:column}.actions{width:100%}.actions .btn{flex:1}.row{padding:12px}.hero h2{font-size:38px}}
  </style>
</head>
<body>
  <div class="shell">
    <header class="topbar"><div class="brand"><div class="brandmark">V</div><div><h1>Personal AI Vault</h1><p>Rak digital asisten Telegram</p></div></div><div class="health"><i class="dot"></i><span id="healthText">Memeriksa layanan…</span></div></header>
    <div class="layout">
      <aside class="sidebar"><nav class="nav"><button class="active" data-view="vault">▣ &nbsp; Vault</button><button data-view="activity">◴ &nbsp; Status aplikasi</button></nav><div class="side-note">File dan database tersimpan di volume persisten yang sama. Selalu aktifkan backup terjadwal pada server produksi.</div></aside>
      <main>
        <section class="hero"><div><div class="eyebrow">Ruang kerja pribadi</div><h2>Semua yang penting,<br>mudah ditemukan.</h2><p>Simpan forward Telegram, kelompokkan ke folder, lalu minta bot mencarinya kembali kapan pun.</p></div><div class="actions"><button class="btn" id="newNote">+ Catatan</button><button class="btn" id="newFolder">+ Folder</button><button class="btn primary" id="uploadFile">↑ Upload file</button><input id="fileInput" type="file" hidden></div></section>
        <section class="stats" id="appStats"><div class="stat"><span>File tersimpan</span><strong id="statFiles">—</strong></div><div class="stat"><span>Catatan vault</span><strong id="statNotes">—</strong></div><div class="stat"><span>Folder</span><strong id="statFolders">—</strong></div><div class="stat"><span>Total storage</span><strong id="statSize">—</strong></div><div class="stat"><span>Memori bot</span><strong id="statMemories">—</strong></div><div class="stat"><span>Request gagal</span><strong id="statFailed">—</strong></div></section>
        <section class="workspace"><div class="toolbar"><label class="search">⌕ <input id="searchInput" placeholder="Cari nama file atau isi catatan…" autocomplete="off"></label><button class="btn" id="refresh">↻ Refresh</button></div><div class="crumbs" id="crumbs"></div><div class="table-head"><span>Nama</span><span>Tipe</span><span>Ukuran</span><span>Diperbarui</span><span></span></div><div id="items"></div></section>
      </main>
    </div>
  </div>
  <dialog id="formDialog"><form method="dialog" class="modal" id="modalForm"><h3 id="modalTitle"></h3><p id="modalHint"></p><div id="modalFields"></div><div class="modal-actions"><button class="btn" type="button" id="modalCancel">Batal</button><button class="btn primary" value="default" id="modalSubmit">Simpan</button></div></form></dialog>
  <div class="toast" id="toast"></div>
  <script>
    const state={parentId:null,folderName:'Root',query:'',items:[]};
    const el=(id)=>document.getElementById(id);const dialog=el('formDialog');
    const esc=(value)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const bytes=(n)=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
    const toast=(message)=>{el('toast').textContent=message;el('toast').classList.add('show');setTimeout(()=>el('toast').classList.remove('show'),2500)};
    async function api(url,options={}){const response=await fetch(url,options);if(!response.ok){let detail='Permintaan gagal';try{detail=(await response.json()).error||detail}catch{}throw new Error(detail)}return response.headers.get('content-type')?.includes('json')?response.json():response}
    async function refreshStats(){const data=await api('/api/status');el('healthText').textContent='Bot aktif · '+formatUptime(data.uptimeSeconds);el('statFiles').textContent=data.vault.files;el('statNotes').textContent=data.vault.notes;el('statFolders').textContent=data.vault.folders;el('statSize').textContent=bytes(data.vault.totalBytes);el('statMemories').textContent=data.memories;el('statFailed').textContent=data.failedRequests}
    const formatUptime=(seconds)=>{const d=Math.floor(seconds/86400),h=Math.floor(seconds%86400/3600),m=Math.floor(seconds%3600/60);return d?d+'h '+h+'j':h?h+'j '+m+'m':m+'m'};
    function renderItems(items){state.items=items;const root=el('items');if(!items.length){root.innerHTML='<div class="empty">Rak ini masih kosong. Upload file, buat folder, atau forward sesuatu ke bot Telegram.</div>';return}root.innerHTML=items.map(item=>{const icon=item.kind==='folder'?'📁':item.kind==='note'?'📝':'📄';const action=item.kind==='file'?'<button class="icon-btn" data-action="download" title="Download">↓</button>':'';return '<div class="row"><div class="name"><div class="icon">'+icon+'</div><button data-action="open" title="Buka">'+esc(item.name)+'</button></div><span class="meta">'+esc(item.kind)+'</span><span class="meta">'+(item.kind==='folder'?'—':bytes(item.sizeBytes))+'</span><span class="meta">'+new Date(item.updatedAt+'Z').toLocaleString('id-ID')+'</span><div class="row-actions">'+action+'<button class="icon-btn" data-action="rename" title="Ubah nama">✎</button><button class="icon-btn" data-action="move" title="Pindah">↗</button><button class="icon-btn" data-action="delete" title="Hapus">×</button></div></div>'}).join('');[...root.querySelectorAll('.row')].forEach((row,index)=>row.addEventListener('click',(event)=>handleItem(event,items[index]))) }
    async function loadItems(){try{const url=state.query?'/api/search?q='+encodeURIComponent(state.query):'/api/items?parentId='+(state.parentId??'');const data=await api(url);renderItems(data.items);el('crumbs').innerHTML='<button id="rootCrumb">Root</button>'+(state.parentId?' <span>/</span> <span>'+esc(state.folderName)+'</span>':'');el('rootCrumb').onclick=()=>{state.parentId=null;state.folderName='Root';state.query='';el('searchInput').value='';loadItems()}}catch(error){toast(error.message)}}
    function openForm(title,hint,fields,onSubmit){el('modalTitle').textContent=title;el('modalHint').textContent=hint;el('modalFields').innerHTML=fields;dialog.returnValue='';dialog.showModal();el('modalForm').onsubmit=async(event)=>{event.preventDefault();try{await onSubmit(new FormData(event.currentTarget));dialog.close();await Promise.all([loadItems(),refreshStats()])}catch(error){toast(error.message)}}}
    function handleItem(event,item){const action=event.target.closest('button')?.dataset.action;if(!action)return;if(action==='open'){if(item.kind==='folder'){state.parentId=item.id;state.folderName=item.name;state.query='';el('searchInput').value='';loadItems()}else if(item.kind==='file'){location.href='/api/items/'+item.id+'/download'}else{openForm(item.name,'Catatan vault','<div class="field"><label>Isi</label><textarea name="content" readonly>'+esc(item.content||'')+'</textarea></div>',async()=>dialog.close())}}if(action==='download')location.href='/api/items/'+item.id+'/download';if(action==='rename')openForm('Ubah nama','Nama harus unik di folder yang sama.','<div class="field"><label>Nama baru</label><input name="name" value="'+esc(item.name)+'" required maxlength="180"></div>',async(data)=>api('/api/items/'+item.id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({name:data.get('name')})}));if(action==='move')openForm('Pindahkan item','Masukkan path folder tujuan. Gunakan / untuk root.','<div class="field"><label>Folder tujuan</label><input name="folder" placeholder="Kerja/Invoice atau /" required></div>',async(data)=>api('/api/items/'+item.id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({folderPath:data.get('folder')})}));if(action==='delete'&&confirm('Hapus '+item.name+(item.kind==='folder'?' beserta seluruh isinya':'')+'?'))api('/api/items/'+item.id,{method:'DELETE'}).then(()=>Promise.all([loadItems(),refreshStats()])).catch((error)=>toast(error.message))}
    el('newFolder').onclick=()=>openForm('Folder baru','Path bertingkat akan dibuat sekaligus.','<div class="field"><label>Nama atau path folder</label><input name="path" placeholder="Kerja/Invoice" required maxlength="500"></div>',async(data)=>api('/api/folders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path:data.get('path'),parentId:state.parentId})}));
    el('newNote').onclick=()=>openForm('Catatan baru','Catatan ini dapat dipakai bot sebagai konteks saat menjawab.','<div class="field"><label>Judul</label><input name="name" required maxlength="180"></div><div class="field"><label>Isi catatan</label><textarea name="content" required maxlength="10000"></textarea></div>',async(data)=>api('/api/notes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:data.get('name'),content:data.get('content'),parentId:state.parentId})}));
    el('uploadFile').onclick=()=>el('fileInput').click();el('fileInput').onchange=async(event)=>{const file=event.target.files[0];if(!file)return;try{await api('/api/files',{method:'POST',headers:{'content-type':file.type||'application/octet-stream','x-file-name':encodeURIComponent(file.name),'x-parent-id':state.parentId??''},body:file});toast('File berhasil diunggah');await Promise.all([loadItems(),refreshStats()])}catch(error){toast(error.message)}finally{event.target.value=''}};
    el('modalCancel').onclick=()=>dialog.close();document.querySelector('[data-view="activity"]').onclick=()=>el('appStats').scrollIntoView({behavior:'smooth',block:'center'});
    let searchTimer;el('searchInput').oninput=(event)=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.query=event.target.value.trim();loadItems()},250)};el('refresh').onclick=()=>Promise.all([loadItems(),refreshStats()]);
    Promise.all([loadItems(),refreshStats()]).catch((error)=>toast(error.message));
  </script>
</body></html>`;
}
