export function dashboardPage(): string {
  return `<!doctype html>
<html lang="id">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="dark">
  <title>Personal AI Control Center</title>
  <style>
    :root{--bg:#080b0a;--panel:#111614;--panel2:#171d1a;--line:#27302b;--line2:#344139;--text:#f2f5f3;--muted:#98a49e;--muted2:#6f7b75;--green:#b7f34a;--green2:#213510;--cyan:#55d6be;--blue:#7ba8ff;--amber:#f7bd61;--danger:#ff837b;--purple:#b58cff;--shadow:0 24px 70px rgba(0,0,0,.32)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 88% -8%,#1c2e19 0,transparent 31%),var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;min-height:100vh}button,input,textarea{font:inherit}button:focus-visible,input:focus-visible,textarea:focus-visible{outline:2px solid var(--green);outline-offset:2px}
    .shell{max-width:1540px;margin:auto;padding:22px}.topbar{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);padding:4px 0 20px}.brand{display:flex;gap:12px;align-items:center}.brandmark{width:38px;height:38px;border-radius:12px;background:var(--green);color:#111;display:grid;place-items:center;font-weight:900}.brand h1{font-size:17px;margin:0;letter-spacing:.01em}.brand p{font-size:12px;color:var(--muted);margin:3px 0 0}.health{display:flex;gap:8px;align-items:center;color:var(--muted);font-size:13px}.dot{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 0 5px rgba(183,243,74,.09)}.dot.error{background:var(--danger);box-shadow:0 0 0 5px rgba(255,131,123,.1)}
    .layout{display:grid;grid-template-columns:230px minmax(0,1fr);gap:22px;padding-top:22px}.sidebar{background:rgba(17,22,20,.72);border:1px solid var(--line);border-radius:18px;padding:14px;height:max-content;position:sticky;top:20px}.nav{display:grid;gap:6px}.nav button{border:0;background:transparent;color:var(--muted);padding:11px 12px;text-align:left;border-radius:10px;cursor:pointer}.nav button.active,.nav button:hover{background:var(--green2);color:var(--green)}.side-note{border-top:1px solid var(--line);margin-top:15px;padding:15px 8px 4px;color:var(--muted);font-size:12px;line-height:1.55}.view[hidden]{display:none!important}
    main{min-width:0}.hero{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin:3px 0 20px}.eyebrow{color:var(--green);text-transform:uppercase;letter-spacing:.16em;font-size:11px;font-weight:750}.hero h2{font-family:Georgia,serif;font-weight:500;font-size:clamp(32px,5vw,54px);line-height:1;margin:7px 0 9px}.hero p{color:var(--muted);margin:0;max-width:710px;line-height:1.5}.actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.btn{border:1px solid var(--line);color:var(--text);background:var(--panel2);padding:10px 14px;border-radius:11px;cursor:pointer;font-weight:650;font-size:13px}.btn:hover{border-color:#536158}.btn.primary{background:var(--green);border-color:var(--green);color:#111}.btn.danger{color:var(--danger)}
    .stats{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px;margin-bottom:20px}.stat,.metric{background:linear-gradient(145deg,rgba(23,29,26,.95),rgba(14,18,16,.94));border:1px solid var(--line);border-radius:15px;padding:16px;box-shadow:var(--shadow)}.stat span,.metric .label{display:block;color:var(--muted);font-size:12px}.stat strong,.metric strong{display:block;font-family:Georgia,serif;font-size:30px;font-weight:500;margin-top:8px}.metric small{display:block;color:var(--muted2);font-size:11px;margin-top:7px;min-height:15px}.metric .accent{color:var(--green)}
    .workspace,.panel{background:rgba(17,22,20,.88);border:1px solid var(--line);border-radius:18px;overflow:hidden;box-shadow:var(--shadow)}.toolbar{display:flex;justify-content:space-between;gap:12px;padding:14px;border-bottom:1px solid var(--line)}.search{display:flex;align-items:center;gap:8px;flex:1;max-width:520px;background:#0b0f0d;border:1px solid var(--line);border-radius:11px;padding:0 12px}.search input{border:0;outline:0;background:transparent;color:var(--text);padding:10px 0;width:100%}.crumbs{display:flex;align-items:center;gap:7px;padding:13px 16px;color:var(--muted);font-size:13px;border-bottom:1px solid var(--line)}.crumbs button{border:0;background:transparent;color:var(--green);cursor:pointer;padding:0}.table-head,.row{display:grid;grid-template-columns:minmax(220px,1fr) 110px 110px 170px 140px;align-items:center;gap:12px}.table-head{padding:10px 16px;color:#77827c;text-transform:uppercase;font-size:10px;letter-spacing:.1em}.row{padding:13px 16px;border-top:1px solid rgba(39,48,43,.72)}.row:hover{background:#141b17}.name{display:flex;align-items:center;gap:11px;min-width:0}.icon{width:36px;height:36px;border:1px solid var(--line);border-radius:10px;display:grid;place-items:center;background:#0d120f}.name button{border:0;background:transparent;color:var(--text);padding:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:left;cursor:pointer}.meta{color:var(--muted);font-size:12px}.row-actions{display:flex;gap:5px;justify-content:flex-end}.icon-btn{border:1px solid transparent;background:transparent;color:var(--muted);cursor:pointer;border-radius:8px;padding:6px 8px}.icon-btn:hover{border-color:var(--line);color:var(--text)}.empty{padding:50px 20px;text-align:center;color:var(--muted);font-size:13px}
    .status-hero{align-items:center}.status-controls{display:flex;align-items:center;gap:8px;flex-wrap:wrap;justify-content:flex-end}.periods{display:flex;padding:3px;background:#0b0f0d;border:1px solid var(--line);border-radius:11px}.periods button{border:0;background:transparent;color:var(--muted);padding:7px 10px;border-radius:8px;cursor:pointer;font-size:12px}.periods button.active{background:var(--green2);color:var(--green)}.updated{font-size:11px;color:var(--muted2);width:100%;text-align:right}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:14px}.metric strong{font-family:inherit;font-size:25px;font-weight:720;letter-spacing:-.035em}.metric strong.dual{display:flex;gap:9px;align-items:baseline}.metric strong.dual span{font:inherit;color:var(--cyan)}.metric strong.dual span+span{color:var(--purple)}
    .chart-grid{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(280px,.75fr);gap:14px;margin:14px 0}.panel-head{display:flex;justify-content:space-between;gap:15px;align-items:flex-start;padding:17px 18px 0}.panel-head h3{font-size:15px;margin:0}.panel-head p{font-size:11px;color:var(--muted);margin:5px 0 0}.legend{display:flex;gap:12px;flex-wrap:wrap;color:var(--muted);font-size:11px}.legend i{display:inline-block;width:8px;height:8px;border-radius:2px;margin-right:5px}.chart{min-height:245px;padding:12px 14px 14px}.chart svg{display:block;width:100%;height:235px;overflow:visible}.chart text{font-family:inherit;font-size:10px;fill:var(--muted2)}.chart .grid{stroke:var(--line);stroke-width:1}.chart-empty{height:220px;display:grid;place-items:center;color:var(--muted);font-size:13px}.donut-wrap{display:grid;place-items:center;padding:24px 18px 16px}.donut{width:150px;height:150px;border-radius:50%;display:grid;place-items:center;position:relative;background:var(--line)}.donut:after{content:"";position:absolute;width:104px;height:104px;border-radius:50%;background:var(--panel)}.donut-label{position:relative;z-index:1;text-align:center}.donut-label strong{display:block;font-size:24px}.donut-label span{font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:.09em}.status-legend{display:grid;gap:9px;padding:0 18px 18px}.status-line{display:flex;justify-content:space-between;gap:8px;color:var(--muted);font-size:12px}.status-line span:first-child:before{content:"";display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--swatch);margin-right:7px}
    .resource-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:9px;margin:14px 0}.resource{border:1px solid var(--line);border-radius:13px;padding:13px;background:rgba(17,22,20,.68)}.resource span{display:block;color:var(--muted);font-size:10px;line-height:1.3}.resource strong{display:block;font-size:19px;margin-top:7px}.data-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:14px 0}.panel-body{padding:14px 18px 18px}.system-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.system-item{padding:11px;border-radius:11px;background:#0c100e;border:1px solid rgba(39,48,43,.7)}.system-item span{display:block;font-size:10px;color:var(--muted)}.system-item strong{display:block;font-size:13px;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mini-table{width:100%;border-collapse:collapse;font-size:12px}.mini-table th{text-align:left;color:var(--muted2);font-size:9px;letter-spacing:.08em;text-transform:uppercase;font-weight:600;padding:8px 7px;border-bottom:1px solid var(--line)}.mini-table td{padding:10px 7px;border-bottom:1px solid rgba(39,48,43,.58);color:var(--muted);vertical-align:top}.mini-table tbody tr:last-child td{border-bottom:0}.mini-table strong{color:var(--text);font-weight:620}.token-in{color:var(--cyan)}.token-out{color:var(--purple)}.scroll-x{overflow-x:auto}.status-pill{display:inline-flex;align-items:center;padding:4px 7px;border-radius:999px;font-size:10px;font-weight:700;text-transform:capitalize;background:#242b27;color:var(--muted)}.status-pill.completed{background:rgba(183,243,74,.12);color:var(--green)}.status-pill.failed,.status-pill.timeout{background:rgba(255,131,123,.12);color:var(--danger)}.status-pill.running{background:rgba(85,214,190,.12);color:var(--cyan)}.status-pill.cancelled{background:rgba(247,189,97,.12);color:var(--amber)}.tools{display:flex;gap:4px;flex-wrap:wrap}.tool{background:#0b0f0d;border:1px solid var(--line);border-radius:6px;padding:3px 5px;font-size:9px;color:var(--muted)}.tool-bars{display:grid;gap:11px}.tool-row{display:grid;grid-template-columns:minmax(90px,1fr) 3fr 32px;gap:10px;align-items:center;font-size:11px;color:var(--muted)}.bar{height:7px;background:#0b0f0d;border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,var(--cyan),var(--green));border-radius:inherit}
    dialog{color:var(--text);background:var(--panel);border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow);width:min(480px,calc(100% - 28px));padding:0}dialog::backdrop{background:rgba(0,0,0,.7)}.modal{padding:20px}.modal h3{margin:0 0 6px}.modal p{color:var(--muted);font-size:13px;margin:0 0 18px}.field{display:grid;gap:7px;margin:12px 0}.field label{font-size:12px;color:var(--muted)}.field input,.field textarea{border:1px solid var(--line);border-radius:10px;background:#0b0f0d;color:var(--text);padding:11px;outline:none}.field textarea{min-height:130px;resize:vertical}.modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.toast{position:fixed;right:22px;bottom:22px;background:#202923;border:1px solid #3a493f;border-radius:12px;padding:12px 15px;box-shadow:var(--shadow);opacity:0;transform:translateY(8px);pointer-events:none;transition:.2s;z-index:5}.toast.show{opacity:1;transform:none}
    @media(max-width:1150px){.metrics{grid-template-columns:repeat(2,1fr)}.resource-grid{grid-template-columns:repeat(4,1fr)}}
    @media(max-width:960px){.layout{grid-template-columns:1fr}.sidebar{position:static}.nav{grid-template-columns:repeat(2,1fr)}.side-note{display:none}.stats{grid-template-columns:repeat(2,1fr)}.table-head{display:none}.row{grid-template-columns:minmax(0,1fr) auto}.row>.meta:nth-of-type(2),.row>.meta:nth-of-type(3){display:none}.row-actions{grid-column:2}.hero{align-items:flex-start;flex-direction:column}.actions,.status-controls{justify-content:flex-start}.updated{text-align:left}.chart-grid,.data-grid{grid-template-columns:1fr}}
    @media(max-width:560px){.shell{padding:14px}.topbar .health span{display:none}.stats,.metrics{grid-template-columns:1fr 1fr}.stat strong{font-size:24px}.toolbar{flex-direction:column}.actions{width:100%}.actions .btn{flex:1}.row{padding:12px}.hero h2{font-size:38px}.resource-grid{grid-template-columns:repeat(2,1fr)}.periods{width:100%;justify-content:space-between}.periods button{flex:1}.system-grid{grid-template-columns:1fr}.metric strong{font-size:21px}}
  </style>
</head>
<body>
  <div class="shell">
    <header class="topbar"><div class="brand"><div class="brandmark">V</div><div><h1>Personal AI Control Center</h1><p>Vault & observabilitas asisten Telegram</p></div></div><div class="health"><i class="dot" id="healthDot"></i><span id="healthText">Memeriksa layanan…</span></div></header>
    <div class="layout">
      <aside class="sidebar"><nav class="nav"><button class="active" data-view="vault">▣ &nbsp; Vault</button><button data-view="observability">◴ &nbsp; Status aplikasi</button></nav><div class="side-note" id="sideNote">File dan database tersimpan di volume persisten yang sama. Selalu aktifkan backup terjadwal pada server produksi.</div></aside>
      <main>
        <section class="view" id="vaultView">
          <section class="hero"><div><div class="eyebrow">Ruang kerja pribadi</div><h2>Semua yang penting,<br>mudah ditemukan.</h2><p>Simpan forward Telegram, kelompokkan ke folder, lalu minta bot mencarinya kembali kapan pun.</p></div><div class="actions"><button class="btn" id="newNote">+ Catatan</button><button class="btn" id="newFolder">+ Folder</button><button class="btn primary" id="uploadFile">↑ Upload file</button><input id="fileInput" type="file" hidden></div></section>
          <section class="stats" id="appStats"><div class="stat"><span>File tersimpan</span><strong id="statFiles">—</strong></div><div class="stat"><span>Catatan vault</span><strong id="statNotes">—</strong></div><div class="stat"><span>Folder</span><strong id="statFolders">—</strong></div><div class="stat"><span>Total storage</span><strong id="statSize">—</strong></div><div class="stat"><span>Memori bot</span><strong id="statMemories">—</strong></div><div class="stat"><span>Request gagal</span><strong id="statFailed">—</strong></div></section>
          <section class="workspace"><div class="toolbar"><label class="search">⌕ <input id="searchInput" placeholder="Cari nama file atau isi catatan…" autocomplete="off"></label><button class="btn" id="refresh">↻ Refresh</button></div><div class="crumbs" id="crumbs"></div><div class="table-head"><span>Nama</span><span>Tipe</span><span>Ukuran</span><span>Diperbarui</span><span></span></div><div id="items"></div></section>
        </section>

        <section class="view" id="observabilityView" hidden>
          <section class="hero status-hero"><div><div class="eyebrow">Observabilitas operasional</div><h2>Kesehatan bot,<br>terukur.</h2><p>Token, performa, reliabilitas, dan riwayat request dalam satu panel. Data berasal dari trace nyata dan tidak menampilkan isi percakapan.</p></div><div class="status-controls"><div class="periods" aria-label="Rentang waktu"><button data-days="1">24 jam</button><button class="active" data-days="7">7 hari</button><button data-days="30">30 hari</button><button data-days="90">90 hari</button></div><button class="btn" id="obsRefresh">↻ Refresh</button><div class="updated" id="obsUpdated">Belum diperbarui</div></div></section>

          <section class="metrics">
            <div class="metric"><span class="label">Total request</span><strong id="metricRequests">—</strong><small id="metricCompleted">— selesai</small></div>
            <div class="metric"><span class="label">Token input / output</span><strong class="dual"><span id="metricInput">—</span><span id="metricOutput">—</span></strong><small id="metricTotalTokens">— total token</small></div>
            <div class="metric"><span class="label">Success rate</span><strong class="accent" id="metricSuccess">—</strong><small>failed + timeout sebagai kegagalan</small></div>
            <div class="metric"><span class="label">Latensi rata-rata</span><strong id="metricLatency">—</strong><small id="metricP95">P95 —</small></div>
            <div class="metric"><span class="label">Chat aktif</span><strong id="metricChats">—</strong><small>identitas dipseudonimkan</small></div>
            <div class="metric"><span class="label">Sedang berjalan</span><strong id="metricRunning">—</strong><small>request aktif saat snapshot</small></div>
            <div class="metric"><span class="label">Gagal / timeout</span><strong id="metricFailed">—</strong><small id="metricCancelled">— dibatalkan</small></div>
            <div class="metric"><span class="label">Uptime proses</span><strong id="metricUptime">—</strong><small id="metricStarted">mulai —</small></div>
          </section>

          <section class="chart-grid">
            <article class="panel"><div class="panel-head"><div><h3>Volume request</h3><p>Aktivitas chatbot per interval</p></div><div class="legend"><span><i style="background:var(--green)"></i>Request</span></div></div><div class="chart" id="volumeChart"></div></article>
            <article class="panel"><div class="panel-head"><div><h3>Status request</h3><p>Distribusi hasil pada periode aktif</p></div></div><div class="donut-wrap"><div class="donut" id="statusDonut"><div class="donut-label"><strong id="donutTotal">—</strong><span>request</span></div></div></div><div class="status-legend" id="statusLegend"></div></article>
          </section>
          <section class="chart-grid">
            <article class="panel"><div class="panel-head"><div><h3>Konsumsi token</h3><p>Input dan output token dari request chat</p></div><div class="legend"><span><i style="background:var(--cyan)"></i>Input</span><span><i style="background:var(--purple)"></i>Output</span></div></div><div class="chart" id="tokenChart"></div></article>
            <article class="panel"><div class="panel-head"><div><h3>Runtime & storage</h3><p>Kondisi proses saat ini</p></div></div><div class="panel-body system-grid" id="systemGrid"></div></article>
          </section>

          <section class="resource-grid" id="resourceGrid"></section>

          <section class="data-grid">
            <article class="panel"><div class="panel-head"><div><h3>Token per chat</h3><p>Agregasi aman tanpa mengekspos Telegram chat ID</p></div></div><div class="panel-body scroll-x"><table class="mini-table"><thead><tr><th>Chat</th><th>Request</th><th>Input</th><th>Output</th><th>Aktif terakhir</th></tr></thead><tbody id="chatRows"></tbody></table></div></article>
            <article class="panel"><div class="panel-head"><div><h3>Performa model</h3><p>Request, token, dan latensi berdasarkan model</p></div></div><div class="panel-body scroll-x"><table class="mini-table"><thead><tr><th>Model</th><th>Request</th><th>Token</th><th>Rata-rata</th></tr></thead><tbody id="modelRows"></tbody></table></div></article>
            <article class="panel"><div class="panel-head"><div><h3>Semua pemakaian AI</h3><p>Chat dan pekerjaan background seperti klasifikasi email</p></div></div><div class="panel-body scroll-x"><table class="mini-table"><thead><tr><th>Purpose</th><th>Model</th><th>Call</th><th>Input / output</th></tr></thead><tbody id="usageRows"></tbody></table></div></article>
            <article class="panel"><div class="panel-head"><div><h3>Tool usage</h3><p>Tool yang dipanggil oleh request terbaru pada periode ini</p></div></div><div class="panel-body"><div class="tool-bars" id="toolRows"></div></div></article>
          </section>

          <section class="panel"><div class="panel-head"><div><h3>Riwayat request</h3><p>Maksimal 50 trace terbaru · isi percakapan tidak ditampilkan</p></div></div><div class="panel-body scroll-x"><table class="mini-table"><thead><tr><th>Waktu / ID</th><th>Chat / input</th><th>Status</th><th>Model</th><th>Token in / out</th><th>Durasi</th><th>Tool</th></tr></thead><tbody id="traceRows"></tbody></table></div></section>
        </section>
      </main>
    </div>
  </div>
  <dialog id="formDialog"><form method="dialog" class="modal" id="modalForm"><h3 id="modalTitle"></h3><p id="modalHint"></p><div id="modalFields"></div><div class="modal-actions"><button class="btn" type="button" id="modalCancel">Batal</button><button class="btn primary" value="default" id="modalSubmit">Simpan</button></div></form></dialog>
  <div class="toast" id="toast"></div>
  <script>
    const state={parentId:null,folderName:'Root',query:'',items:[],days:7,observabilityLoaded:false};
    const el=(id)=>document.getElementById(id);const dialog=el('formDialog');
    const esc=(value)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const formatNumber=(value)=>new Intl.NumberFormat('id-ID').format(Number(value)||0);
    const compact=(value)=>new Intl.NumberFormat('id-ID',{notation:'compact',maximumFractionDigits:1}).format(Number(value)||0);
    const bytes=(n)=>n<1024?formatNumber(n)+' B':n<1048576?(n/1024).toFixed(1)+' KB':n<1073741824?(n/1048576).toFixed(1)+' MB':(n/1073741824).toFixed(1)+' GB';
    const duration=(ms)=>ms===null||ms===undefined?'—':ms<1000?formatNumber(ms)+' ms':ms<60000?(ms/1000).toFixed(1)+' dtk':(ms/60000).toFixed(1)+' mnt';
    const formatUptime=(seconds)=>{const d=Math.floor(seconds/86400),h=Math.floor(seconds%86400/3600),m=Math.floor(seconds%3600/60);return d?d+' hari '+h+' jam':h?h+' jam '+m+' mnt':m?m+' menit':Math.max(0,Math.floor(seconds))+' detik'};
    const localDate=(value,short=false)=>{if(!value)return'—';const options=short?{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}:{dateStyle:'medium',timeStyle:'short'};return new Date(value).toLocaleString('id-ID',options)};
    const toast=(message)=>{el('toast').textContent=message;el('toast').classList.add('show');setTimeout(()=>el('toast').classList.remove('show'),2500)};
    async function api(url,options={}){const response=await fetch(url,options);if(!response.ok){let detail='Permintaan gagal';try{detail=(await response.json()).error||detail}catch{}throw new Error(detail)}return response.headers.get('content-type')?.includes('json')?response.json():response}

    async function refreshStats(){const data=await api('/api/status');el('healthText').textContent='Proses aktif · '+formatUptime(data.uptimeSeconds);el('healthDot').classList.remove('error');el('statFiles').textContent=data.vault.files;el('statNotes').textContent=data.vault.notes;el('statFolders').textContent=data.vault.folders;el('statSize').textContent=bytes(data.vault.totalBytes);el('statMemories').textContent=data.memories;el('statFailed').textContent=data.failedRequests}
    function renderItems(items){state.items=items;const root=el('items');if(!items.length){root.innerHTML='<div class="empty">Rak ini masih kosong. Upload file, buat folder, atau forward sesuatu ke bot Telegram.</div>';return}root.innerHTML=items.map(item=>{const icon=item.kind==='folder'?'📁':item.kind==='note'?'📝':'📄';const action=item.kind==='file'?'<button class="icon-btn" data-action="download" title="Download">↓</button>':'';return '<div class="row"><div class="name"><div class="icon">'+icon+'</div><button data-action="open" title="Buka">'+esc(item.name)+'</button></div><span class="meta">'+esc(item.kind)+'</span><span class="meta">'+(item.kind==='folder'?'—':bytes(item.sizeBytes))+'</span><span class="meta">'+new Date(item.updatedAt+'Z').toLocaleString('id-ID')+'</span><div class="row-actions">'+action+'<button class="icon-btn" data-action="rename" title="Ubah nama">✎</button><button class="icon-btn" data-action="move" title="Pindah">↗</button><button class="icon-btn" data-action="delete" title="Hapus">×</button></div></div>'}).join('');[...root.querySelectorAll('.row')].forEach((row,index)=>row.addEventListener('click',(event)=>handleItem(event,items[index])))}
    async function loadItems(){try{const url=state.query?'/api/search?q='+encodeURIComponent(state.query):'/api/items?parentId='+(state.parentId??'');const data=await api(url);renderItems(data.items);el('crumbs').innerHTML='<button id="rootCrumb">Root</button>'+(state.parentId?' <span>/</span> <span>'+esc(state.folderName)+'</span>':'');el('rootCrumb').onclick=()=>{state.parentId=null;state.folderName='Root';state.query='';el('searchInput').value='';loadItems()}}catch(error){toast(error.message)}}
    function openForm(title,hint,fields,onSubmit){el('modalTitle').textContent=title;el('modalHint').textContent=hint;el('modalFields').innerHTML=fields;dialog.returnValue='';dialog.showModal();el('modalForm').onsubmit=async(event)=>{event.preventDefault();try{await onSubmit(new FormData(event.currentTarget));dialog.close();await Promise.all([loadItems(),refreshStats()])}catch(error){toast(error.message)}}}
    function handleItem(event,item){const action=event.target.closest('button')?.dataset.action;if(!action)return;if(action==='open'){if(item.kind==='folder'){state.parentId=item.id;state.folderName=item.name;state.query='';el('searchInput').value='';loadItems()}else if(item.kind==='file'){location.href='/api/items/'+item.id+'/download'}else{openForm(item.name,'Catatan vault','<div class="field"><label>Isi</label><textarea name="content" readonly>'+esc(item.content||'')+'</textarea></div>',async()=>dialog.close())}}if(action==='download')location.href='/api/items/'+item.id+'/download';if(action==='rename')openForm('Ubah nama','Nama harus unik di folder yang sama.','<div class="field"><label>Nama baru</label><input name="name" value="'+esc(item.name)+'" required maxlength="180"></div>',async(data)=>api('/api/items/'+item.id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({name:data.get('name')})}));if(action==='move')openForm('Pindahkan item','Masukkan path folder tujuan. Gunakan / untuk root.','<div class="field"><label>Folder tujuan</label><input name="folder" placeholder="Kerja/Invoice atau /" required></div>',async(data)=>api('/api/items/'+item.id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({folderPath:data.get('folder')})}));if(action==='delete'&&confirm('Hapus '+item.name+(item.kind==='folder'?' beserta seluruh isinya':'')+'?'))api('/api/items/'+item.id,{method:'DELETE'}).then(()=>Promise.all([loadItems(),refreshStats()])).catch((error)=>toast(error.message))}

    function labelForPoint(value,days){const date=new Date(value);return days===1?date.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}):date.toLocaleDateString('id-ID',{day:'2-digit',month:'short'})}
    function renderLineChart(rootId,data,key,color){const root=el(rootId);const values=data.map(point=>Number(point[key])||0);const max=Math.max(...values,0);if(max===0){root.innerHTML='<div class="chart-empty">Belum ada aktivitas pada periode ini.</div>';return}const width=800,height=235,left=42,right=12,top=14,bottom=30,usableW=width-left-right,usableH=height-top-bottom;const scaleMax=max*1.12||1;const coords=values.map((value,index)=>{const x=left+(data.length===1?usableW/2:index*usableW/(data.length-1));const y=top+usableH-(value/scaleMax)*usableH;return[x,y]});const path=coords.map((point,index)=>(index?'L':'M')+point[0].toFixed(1)+' '+point[1].toFixed(1)).join(' ');const area=path+' L '+coords[coords.length-1][0].toFixed(1)+' '+(top+usableH)+' L '+coords[0][0].toFixed(1)+' '+(top+usableH)+' Z';let svg='<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="Grafik volume request">';for(let i=0;i<4;i++){const y=top+i*usableH/3;svg+='<line class="grid" x1="'+left+'" y1="'+y+'" x2="'+(width-right)+'" y2="'+y+'"></line><text x="0" y="'+(y+4)+'">'+compact(scaleMax*(1-i/3))+'</text>'}svg+='<path d="'+area+'" fill="'+color+'" opacity=".09"></path><path d="'+path+'" fill="none" stroke="'+color+'" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"></path>';coords.forEach((point,index)=>{if(data.length<35||index%Math.ceil(data.length/20)===0)svg+='<circle cx="'+point[0]+'" cy="'+point[1]+'" r="2.5" fill="'+color+'"><title>'+esc(labelForPoint(data[index].date,state.days))+': '+formatNumber(values[index])+'</title></circle>'});const labelStep=Math.max(1,Math.ceil(data.length/6));data.forEach((point,index)=>{if(index%labelStep===0||index===data.length-1)svg+='<text x="'+coords[index][0]+'" y="'+(height-7)+'" text-anchor="middle">'+esc(labelForPoint(point.date,state.days))+'</text>'});root.innerHTML=svg+'</svg>'}
    function renderTokenChart(data){const root=el('tokenChart');const totals=data.map(point=>(Number(point.inputTokens)||0)+(Number(point.outputTokens)||0));const max=Math.max(...totals,0);if(max===0){root.innerHTML='<div class="chart-empty">Token akan muncul setelah chatbot menerima request.</div>';return}const width=800,height=235,left=42,right=12,top=14,bottom=30,usableW=width-left-right,usableH=height-top-bottom,slot=usableW/data.length,barWidth=Math.max(2,Math.min(28,slot*.62));let svg='<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="Grafik token input dan output">';for(let i=0;i<4;i++){const y=top+i*usableH/3;svg+='<line class="grid" x1="'+left+'" y1="'+y+'" x2="'+(width-right)+'" y2="'+y+'"></line><text x="0" y="'+(y+4)+'">'+compact(max*(1-i/3))+'</text>'}data.forEach((point,index)=>{const input=Number(point.inputTokens)||0,output=Number(point.outputTokens)||0,x=left+slot*index+(slot-barWidth)/2,inputH=input/max*usableH,outputH=output/max*usableH,yBase=top+usableH;svg+='<rect x="'+x+'" y="'+(yBase-inputH)+'" width="'+barWidth+'" height="'+inputH+'" fill="var(--cyan)" rx="2"><title>'+esc(labelForPoint(point.date,state.days))+' · Input '+formatNumber(input)+'</title></rect><rect x="'+x+'" y="'+(yBase-inputH-outputH)+'" width="'+barWidth+'" height="'+outputH+'" fill="var(--purple)" rx="2"><title>'+esc(labelForPoint(point.date,state.days))+' · Output '+formatNumber(output)+'</title></rect>'});const labelStep=Math.max(1,Math.ceil(data.length/6));data.forEach((point,index)=>{if(index%labelStep===0||index===data.length-1)svg+='<text x="'+(left+slot*index+slot/2)+'" y="'+(height-7)+'" text-anchor="middle">'+esc(labelForPoint(point.date,state.days))+'</text>'});root.innerHTML=svg+'</svg>'}
    const statusMeta={completed:['Selesai','#b7f34a'],failed:['Gagal','#ff837b'],timeout:['Timeout','#f7bd61'],cancelled:['Dibatalkan','#b58cff'],running:['Berjalan','#55d6be']};
    function renderStatuses(statuses,total){const counts=new Map(statuses.map(item=>[item.status,item.count]));const ordered=['completed','failed','timeout','cancelled','running'].map(status=>({status,count:counts.get(status)||0}));let cursor=0;const segments=[];ordered.forEach(item=>{if(!total||!item.count)return;const start=cursor,end=cursor+item.count/total*360;segments.push(statusMeta[item.status][1]+' '+start+'deg '+end+'deg');cursor=end});el('statusDonut').style.background=segments.length?'conic-gradient('+segments.join(',')+')':'var(--line)';el('donutTotal').textContent=compact(total);el('statusLegend').innerHTML=ordered.map(item=>'<div class="status-line" style="--swatch:'+statusMeta[item.status][1]+'"><span>'+statusMeta[item.status][0]+'</span><strong>'+formatNumber(item.count)+'</strong></div>').join('')}
    function emptyRow(columns,text){return'<tr><td colspan="'+columns+'"><div class="empty">'+esc(text)+'</div></td></tr>'}
    function renderObservability(data){const overview=data.overview;el('metricRequests').textContent=formatNumber(overview.requests);el('metricCompleted').textContent=formatNumber(overview.completed)+' selesai';el('metricInput').textContent=compact(overview.inputTokens);el('metricOutput').textContent=compact(overview.outputTokens);el('metricTotalTokens').textContent=formatNumber(overview.totalTokens)+' total token';el('metricSuccess').textContent=overview.ratedRequests?overview.successRate.toFixed(1)+'%':'—';el('metricLatency').textContent=duration(overview.averageLatencyMs);el('metricP95').textContent='P95 '+duration(overview.p95LatencyMs);el('metricChats').textContent=formatNumber(overview.uniqueChats);el('metricRunning').textContent=formatNumber(overview.running);el('metricFailed').textContent=formatNumber(overview.failed+overview.timedOut);el('metricCancelled').textContent=formatNumber(overview.cancelled)+' dibatalkan';el('metricUptime').textContent=formatUptime(data.health.uptimeSeconds);el('metricStarted').textContent='mulai '+localDate(data.health.startedAt,true);el('obsUpdated').textContent='Diperbarui '+localDate(data.generatedAt,true)+' · otomatis 30 detik';
      renderLineChart('volumeChart',data.series,'requests','#b7f34a');renderTokenChart(data.series);renderStatuses(data.statuses,overview.requests);
      const systems=[['Status','Sehat'],['Runtime',data.health.runtime],['Heap terpakai',bytes(data.health.heapUsedBytes)],['Resident memory',bytes(data.health.residentMemoryBytes)],['Ukuran database',bytes(data.health.databaseBytes)],['Mulai proses',localDate(data.health.startedAt,true)]];el('systemGrid').innerHTML=systems.map(item=>'<div class="system-item"><span>'+esc(item[0])+'</span><strong>'+esc(item[1])+'</strong></div>').join('');
      const resources=[['Riwayat pesan',data.resources.conversationMessages],['Memori bot',data.resources.memories],['Item vault',data.resources.vaultItems],['Email rule aktif',data.resources.activeEmailRules],['Email mengantre',data.resources.pendingEmailNotifications],['Email dead-letter',data.resources.deadLetterEmails],['Failure terminal',data.resources.terminalEmailFailures]];el('resourceGrid').innerHTML=resources.map(item=>'<div class="resource"><span>'+esc(item[0])+'</span><strong>'+formatNumber(item[1])+'</strong></div>').join('');
      el('chatRows').innerHTML=data.chats.length?data.chats.map(row=>'<tr><td><strong>'+esc(row.chat)+'</strong></td><td>'+formatNumber(row.requests)+'</td><td class="token-in">'+formatNumber(row.inputTokens)+'</td><td class="token-out">'+formatNumber(row.outputTokens)+'</td><td>'+localDate(row.lastActiveAt,true)+'</td></tr>').join(''):emptyRow(5,'Belum ada trace chat pada periode ini.');
      el('modelRows').innerHTML=data.models.length?data.models.map(row=>'<tr><td><strong>'+esc(row.model)+'</strong></td><td>'+formatNumber(row.requests)+'</td><td><span class="token-in">'+compact(row.inputTokens)+'</span> / <span class="token-out">'+compact(row.outputTokens)+'</span></td><td>'+duration(row.averageLatencyMs)+'</td></tr>').join(''):emptyRow(4,'Belum ada data model.');
      el('usageRows').innerHTML=data.usage.length?data.usage.map(row=>'<tr><td><strong>'+esc(row.purpose)+'</strong></td><td>'+esc(row.model)+'</td><td>'+formatNumber(row.calls)+'</td><td><span class="token-in">'+formatNumber(row.inputTokens)+'</span> / <span class="token-out">'+formatNumber(row.outputTokens)+'</span></td></tr>').join(''):emptyRow(4,'Belum ada pemakaian AI pada periode ini.');
      const maxTool=Math.max(...data.tools.map(row=>row.calls),0);el('toolRows').innerHTML=data.tools.length?data.tools.map(row=>'<div class="tool-row"><strong>'+esc(row.tool)+'</strong><div class="bar"><i style="width:'+Math.max(4,row.calls/maxTool*100)+'%"></i></div><span>'+formatNumber(row.calls)+'</span></div>').join(''):'<div class="empty">Belum ada tool yang dipakai.</div>';
      el('traceRows').innerHTML=data.recent.length?data.recent.map(row=>'<tr><td><strong>#'+esc(row.requestId)+'</strong><br>'+localDate(row.startedAt,true)+'</td><td><strong>'+esc(row.chat)+'</strong><br>'+esc(row.inputKind==='image'?'Teks + gambar':'Teks')+'</td><td><span class="status-pill '+esc(row.status)+'" title="'+esc(row.errorMessage||'')+'">'+esc(statusMeta[row.status]?.[0]||row.status)+'</span></td><td>'+esc(row.model)+'</td><td><span class="token-in">'+formatNumber(row.inputTokens)+'</span> / <span class="token-out">'+formatNumber(row.outputTokens)+'</span></td><td>'+duration(row.elapsedMs)+'</td><td><div class="tools">'+(row.tools.length?row.tools.map(tool=>'<span class="tool">'+esc(tool)+'</span>').join(''):'—')+'</div></td></tr>').join(''):emptyRow(7,'Belum ada riwayat request pada periode ini.')}
    async function loadObservability(silent=false){if(!silent)el('obsUpdated').textContent='Memuat metrik…';try{const data=await api('/api/observability?days='+state.days);renderObservability(data);state.observabilityLoaded=true}catch(error){el('obsUpdated').textContent='Gagal memuat metrik';if(!silent)toast(error.message);throw error}}
    function showView(view){const isStatus=view==='observability';el('vaultView').hidden=isStatus;el('observabilityView').hidden=!isStatus;document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));el('sideNote').textContent=isStatus?'Dashboard memakai trace operasional dan usage event. Isi chat tidak ditampilkan, dan ID chat dipseudonimkan.':'File dan database tersimpan di volume persisten yang sama. Selalu aktifkan backup terjadwal pada server produksi.';history.replaceState(null,'',isStatus?'#status':'#vault');if(isStatus&&!state.observabilityLoaded)loadObservability().catch(()=>undefined)}

    el('newFolder').onclick=()=>openForm('Folder baru','Path bertingkat akan dibuat sekaligus.','<div class="field"><label>Nama atau path folder</label><input name="path" placeholder="Kerja/Invoice" required maxlength="500"></div>',async(data)=>api('/api/folders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path:data.get('path'),parentId:state.parentId})}));
    el('newNote').onclick=()=>openForm('Catatan baru','Catatan ini dapat dipakai bot sebagai konteks saat menjawab.','<div class="field"><label>Judul</label><input name="name" required maxlength="180"></div><div class="field"><label>Isi catatan</label><textarea name="content" required maxlength="10000"></textarea></div>',async(data)=>api('/api/notes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:data.get('name'),content:data.get('content'),parentId:state.parentId})}));
    el('uploadFile').onclick=()=>el('fileInput').click();el('fileInput').onchange=async(event)=>{const file=event.target.files[0];if(!file)return;try{await api('/api/files',{method:'POST',headers:{'content-type':file.type||'application/octet-stream','x-file-name':encodeURIComponent(file.name),'x-parent-id':state.parentId??''},body:file});toast('File berhasil diunggah');await Promise.all([loadItems(),refreshStats()])}catch(error){toast(error.message)}finally{event.target.value=''}};
    el('modalCancel').onclick=()=>dialog.close();document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>showView(button.dataset.view));document.querySelectorAll('[data-days]').forEach(button=>button.onclick=()=>{state.days=Number(button.dataset.days);document.querySelectorAll('[data-days]').forEach(item=>item.classList.toggle('active',item===button));loadObservability().catch(()=>undefined)});
    let searchTimer;el('searchInput').oninput=(event)=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.query=event.target.value.trim();loadItems()},250)};el('refresh').onclick=()=>Promise.all([loadItems(),refreshStats()]);el('obsRefresh').onclick=()=>loadObservability().catch(()=>undefined);
    Promise.all([loadItems(),refreshStats()]).catch((error)=>{el('healthDot').classList.add('error');el('healthText').textContent='Layanan bermasalah';toast(error.message)}).finally(()=>{if(location.hash==='#status')showView('observability')});setInterval(()=>{if(!el('observabilityView').hidden)loadObservability(true).catch(()=>undefined)},30000);
  </script>
</body></html>`;
}
